services:
  - type: web
    name: clinicrush-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production